FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y iputils-ping 
RUN apt-get install -y net-tools
RUN apt-get install -y default-jdk
RUN apt-get install -y scala
RUN apt-get install -y openssh-server openssh-client
EXPOSE 80 443 8080 4040

